spring:
  datasource:
    url: jdbc:sqlserver://my-server0147.database.windows.net:1433;database=my-db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: rahul
    password: Fomqe@0147/-
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191


